-- PostgreSQL - Drop PAGOPA_IBAN_CHECK table

DROP TABLE IF EXISTS PAGOPA_IBAN_CHECK CASCADE;
DROP SEQUENCE IF EXISTS seq_pagopa_iban_check;

-- PostgreSQL - Drop PAGOPA_EC_CHECK table

DROP TABLE IF EXISTS PAGOPA_EC_CHECK CASCADE;
DROP SEQUENCE IF EXISTS seq_pagopa_ec_check;
