-- HSQLDB (H2) DDL for IBAN_PAGOPA_TEMP table
-- Compatible with H2 database used for development/testing

CREATE TABLE IBAN_PAGOPA_TEMP (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_intermediario   VARCHAR(35) NOT NULL,
    ci_fiscal_code      VARCHAR(35) NOT NULL,
    ci_name             VARCHAR(255),
    iban                VARCHAR(35) NOT NULL,
    status              VARCHAR(255),
    validity_date       TIMESTAMP WITH TIME ZONE,
    description         VARCHAR(512),
    label               VARCHAR(1024),
    check_stato         VARCHAR(35),
    check_motivo        VARCHAR(1024)
);

-- Indexes
CREATE INDEX idx_ipt_ci_fiscal_code ON IBAN_PAGOPA_TEMP(ci_fiscal_code);
CREATE INDEX idx_ipt_iban ON IBAN_PAGOPA_TEMP(iban);
CREATE INDEX idx_ipt_cod_intermediario ON IBAN_PAGOPA_TEMP(cod_intermediario);
CREATE INDEX idx_ipt_check_stato ON IBAN_PAGOPA_TEMP(check_stato);
CREATE INDEX idx_ipt_fiscal_code_iban ON IBAN_PAGOPA_TEMP(ci_fiscal_code, iban);
