-- SQL Server - Drop PAGOPA_IBAN_CHECK table

IF OBJECT_ID('dbo.PAGOPA_IBAN_CHECK', 'U') IS NOT NULL
    DROP TABLE dbo.PAGOPA_IBAN_CHECK;

-- SQL Server - Drop PAGOPA_EC_CHECK table

IF OBJECT_ID('dbo.PAGOPA_EC_CHECK', 'U') IS NOT NULL
    DROP TABLE dbo.PAGOPA_EC_CHECK;
